import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";

import Script from 'next/script';

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const apiKey = process.env.NEXT_PUBLIC_GEOLONIA_API_KEY;
  const src = `https://cdn.geolonia.com/v1/embed?geolonia-api-key=${apiKey}`;

  return (
    <html lang="en" className={`${geist.variable}`}>
      <head>
        <link rel="stylesheet" href="https://cdn.geolonia.com/v1/style.css" />   
        <Script src={src} />     
      </head>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        <Toaster />{}
      </body>
    </html>
  );
}
